<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    async function foo(){
        console.log(1)
        //异步函数中的异常,会被作为reject的值
        throw new Error('error')
        console.log(2)
    }



    foo().catch(err => {
        console.log(err)
    })


    console.log('还会执行')

</script>
</body>
</html>